<script src="{{ asset('/users/userjs/jquery-3.2.1.min.js'); }}"></script>
<script src="{{ asset('/users/userjs/popper.min.js'); }}"></script>
<script src="{{ asset('/users/userjs/bootstrap.min.js'); }}"></script>
<!-- ALL PLUGINS -->
<script src="{{ asset('/users/userjs/jquery.superslides.min.js'); }}"></script>
<script src="{{ asset('/users/userjs/bootstrap-select.js'); }}"></script>
<script src="{{ asset('/users/userjs/inewsticker.js'); }}"></script>
<script src="{{ asset('/users/userjs/bootsnav.js'); }}"></script>
<script src="{{ asset('/users/userjs/images-loded.min.js'); }}"></script>
<script src="{{ asset('/users/userjs/isotope.min.js'); }}"></script>
<script src="{{ asset('/users/userjs/owl.carousel.min.js'); }}"></script>
<script src="{{ asset('/users/userjs/baguetteBox.min.js'); }}"></script>
<script src="{{ asset('/users/userjs/form-validator.min.js'); }}"></script>
<script src="{{ asset('/users/userjs/contact-form-script.js'); }}"></script>
<script src="{{ asset('/users/userjs/custom.js'); }}"></script>